export const ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  CHARACTER_NOT_FOUND: 'CHARACTER_NOT_FOUND',
  QUEST_NOT_FOUND: 'QUEST_NOT_FOUND',
  QUEST_ALREADY_COMPLETED: 'QUEST_ALREADY_COMPLETED',
  QUEST_DOCUMENT_REQUIRED: 'QUEST_DOCUMENT_REQUIRED',
  QUEST_TEST_REQUIRED: 'QUEST_TEST_REQUIRED',
  QUEST_TEST_NOT_FOUND: 'QUEST_TEST_NOT_FOUND',
  QUEST_TEST_ANSWERS_INVALID: 'QUEST_TEST_ANSWERS_INVALID',
  QUEST_VIDEO_REQUIRED: 'QUEST_VIDEO_REQUIRED',
  QUEST_VIDEO_NOT_FOUND: 'QUEST_VIDEO_NOT_FOUND',
  SKILL_NOT_FOUND: 'SKILL_NOT_FOUND',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  [ERROR_CODES.VALIDATION_FAILED]: 'Request validation failed',
  [ERROR_CODES.UNAUTHORIZED]: 'Authentication required',
  [ERROR_CODES.FORBIDDEN]: 'Access forbidden',
  [ERROR_CODES.NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.CONFLICT]: 'Resource conflict',
  [ERROR_CODES.INTERNAL_ERROR]: 'Internal server error',

  [ERROR_CODES.CHARACTER_NOT_FOUND]: 'Character not found',
  [ERROR_CODES.QUEST_NOT_FOUND]: 'Quest not found',
  [ERROR_CODES.QUEST_ALREADY_COMPLETED]: 'Quest already completed',
  [ERROR_CODES.QUEST_DOCUMENT_REQUIRED]: 'Approved document is required to complete this quest',
  [ERROR_CODES.QUEST_TEST_REQUIRED]: 'You must pass the test to complete this quest',
  [ERROR_CODES.QUEST_TEST_NOT_FOUND]: 'No test is configured for this quest',
  [ERROR_CODES.QUEST_TEST_ANSWERS_INVALID]: 'Submitted answers do not match the question set',
  [ERROR_CODES.QUEST_VIDEO_REQUIRED]: 'You must watch the video to complete this quest',
  [ERROR_CODES.QUEST_VIDEO_NOT_FOUND]: 'No video is configured for this quest',
  [ERROR_CODES.SKILL_NOT_FOUND]: 'Skill not found',
  [ERROR_CODES.EMPLOYEE_NOT_FOUND]: 'Employee not found',
};
